news/urls.py
from django.urls import path
from news.views import *

app_name = "news"
urlpatterns = [
    path('', index, name='index'),
    path('homepage/', home, name='homepage'),
    path("articolo/<int:pk>", articoloDetailView, name="articolo_detail"),
    path("giornalista/<int:pk>", giornalistaDetailView, name="giornalista_detail"),
    path("lista_articoli/", listaArticoli, name="lista_articoli"),
    path("lista_articoli/<int:pk>", listaArticoli, name="lista_articoli"),
    path("query_base/", queryBase, name="query_base"),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from primo_progetto.views import index_root

urlpatterns = [
    path('', index_root),
    path('admin/', admin.site.urls),
    path('prima_app/', include("prima_app.urls", namespace="prima_app")),
    path('seconda_app/', include("seconda_app.urls", namespace="seconda_app")),
    path('prova_pratica_0/', include("prova_pratica_0.urls", namespace="prova_pratica_0")),
    path('news/', include("news.urls", namespace="news")),
    path('voti/', include("voti.urls", namespace="voti")),
]

news/models.py
from django.db import models

class Giornalista(models.Model):
    """ Modello generico di un giornalisa """
    nome = models.CharField(max_length=20)
    cognome = models.CharField(max_length=20)
    anno_di_nascita = models.DateField(blank=True)

    def __str__(self):
        return self.nome + ' ' + self.cognome

    class Meta:
        verbose_name = 'Giornalista'
        verbose_name_plural = 'Giornalisti'

class Articolo(models.Model):
    """ Modello generico di un articolo di news """
    titolo = models.CharField(max_length=20)
    contenuto = models.TextField()
    giornalista = models.ForeignKey(Giornalista, on_delete=models.CASCADE, related_name='articoli')
    data = models.DateField(blank=True)
    visualizzazioni = models.IntegerField(default=0, blank=True)

    def __str__(self):
        return self.titolo

    class Meta:
        verbose_name = 'Articolo'
        verbose_name_plural = 'Articoli'

news/views.py
from django.shortcuts import render, get_object_or_404
from news.models import *
import datetime

def home(request):
    """
    a = ""
    g = ""

    for art in Articolo.objects.all():
        a += (art.titolo + "<br>")

    for gio in Giornalista.objects.all():
        g += (gio.nome + "<br>")
    response = "Articoli:<br>" + a + "<br>Giornalista:<br>" + g

    Dati scritti in Stringa
    """
    """
    a = []
    g = []

    for art in Articolo.objects.all():
        a.append(art.titolo)

    for gio in Giornalista.objects.all():
        g.append(gio.nome)
    response = str(a) + "<br>" + str(g)
    print(response)
    Dati scritti in una lista
    """
    # Dati scritti in un dizionario e poi stampandi nel template
    articoli = Articolo.objects.all()
    giornalisti = Giornalista.objects.all()
    context = {"articoli": articoli, "giornalisti": giornalisti}
    #print(context)

    return render(request, "news/homepage.html", context)

def articoloDetailView(request, pk):
    # articolo = Articolo.objects.get(pk=pk)
    articolo = get_object_or_404(Articolo, pk=pk)
    context = {"articolo": articolo}
    return render(request, "news/articolo_detail.html", context)

def giornalistaDetailView(request, pk):
    # articolo = Articolo.objects.get(pk=pk)
    giornalista = get_object_or_404(Giornalista, pk=pk)
    articoli = Articolo.objects.filter(giornalista__id=pk)
    context = {"giornalista": giornalista,
               "articoli": articoli}
    return render(request, "news/giornalista_detail.html", context)

def listaArticoli(request, pk=None):
    articoli = Articolo.objects.all() if pk is None else Articolo.objects.filter(giornalista_id=pk)
    is_giornalista = True if pk is not None else False
    is_vuoto = True if not articoli else False
    context = {"articoli": articoli, "is_giornalista": is_giornalista, "is_vuoto": is_vuoto}
    return render(request, 'lista_articoli.html', context)

def index(request):
    return render(request, 'news/index.html')

def queryBase(request):
    # 1. Tutti gli articoli scritti da giornalisti di un certo cognome:
    articoli_cognome = Articolo.objects.filter(giornalista__cognome='Rossi')

    # 2. Totale
    numero_totale_articoli = Articolo.objects.count()

    # 3. Conta il numero di articoli scritti da un giornalista specifico:
    giornalista_6 = Giornalista.objects.get(id=6)
    numero_articoli_giornalista_1 = Articolo.objects.filter(giornalista=giornalista_6).count()

    # 4. Ordinare gli articoli per numero di visualizzazioni in ordine decrescente:
    articoli_ordinati = Articolo.objects.order_by('-visualizzazioni')

    # 5. tutti gli articoli che non hanno visualizzazioni:
    articoli_senza_visualizzazioni = Articolo.objects.filter(visualizzazioni=0)

    # 6. articolo più visualizzato
    articolo_piu_visualizzato = Articolo.objects.order_by('-visualizzazioni').first()

    # 7. Tutti i giornalisti nati dopo una certa data:
    giornalisti_data = Giornalista.objects.filter(anno_di_nascita__gt=datetime.date(1990, 1, 1))

    # 8. tutti gli articoli pubblicati in una data specifica:
    articoli_del_giorno = Articolo.objects.filter(data=datetime.date(2023, 1, 1))

    # 9. tutti gli articoli pubblicati in un intervallo di date
    articoli_periodo = Articolo.objects.filter(
        data__range=(datetime.date(2023, 1, 1), datetime.date(2023, 12, 31))
    )

    # 10. gli articoli scritti da giornalisti nati prima del 1980:
    giornalisti_nati = Giornalista.objects.filter(anno_di_nascita__lt=datetime.date(1980, 1, 1))
    articoli_giornalisti_nati = Articolo.objects.filter(giornalista__in=giornalisti_nati)

    # 11. il giornalista più giovane:
    giornalista_giovane = Giornalista.objects.order_by('anno_di_nascita').first()

    # 12. il giornalista più anziano:
    giornalista_anziano = Giornalista.objects.order_by('-anno_di_nascita').first()

    # 13. gli ultimi 5 articoli pubblicati:
    ultimi_5_articoli = Articolo.objects.order_by('-data')[:5]

    # 14. tutti gli articoli con un certo numero minimo di visualizzazioni:
    articoli_minime_visualizzazioni = Articolo.objects.filter(visualizzazioni__gte=100)

    # 15. tutti gli articoli che contengono una certa parola nel titolo:
    articoli_parola = Articolo.objects.filter(titolo__icontains='importante')

    # 16 Articoli pubblicati in un certo mese di un anno specifico
    artioli_mese_anno = Articolo.objects.filter(data__month=1, data__year=2023)

    # 17 Giornalista con almeno un articolo con più di 100 visualizzazioni, attraverso la foreign key dell'articolo
    giornalisti_con_articoli_popolari = Giornalista.objects.filter(articoli__visualizzazioni__gte=100).distinct()

    # Utilizzo di piú condizioni di selezione
    data = datetime.date(1990, 1, 1)
    visualizzazioni = 50
    # Per mettere in AND le condizioni separarle con la virgola
    # 18
    articoli_con_and = Articolo.objects.filter(giornalista__anno_di_nascita__gt=data, visualizzazioni__gte=visualizzazioni)

    # Per mettere in OR le condizioni utilizzare l'operatore Q
    from django.db.models import Q
    # 19
    articoli_con_or = Articolo.objects.filter(Q(giornalista__anno_di_nascita__gt=data) | Q(visualizzazioni__gte=visualizzazioni))

    # Per il NOT (~) utilizzare l'operatore Q
    # 20 con filter
    # articoli_con_not = Articolo.objects.filter(~Q(giornalista__anno_di_nascita__gt=data))
    # oppure il metodo exclude
    articoli_con_not = Articolo.objects.exclude(giornalista__anno_di_nascita__gt=data)


    # Creare il dizionario context
    context = {
        'articoli_cognome': articoli_cognome,
        'numero_totale_articoli': numero_totale_articoli,
        'numero_articoli_giornalista_1': numero_articoli_giornalista_1,
        'articoli_ordinati': articoli_ordinati,
        'articoli_senza_visualizzazioni': articoli_senza_visualizzazioni,
        'articolo_piu_visualizzato': articolo_piu_visualizzato,
        'giornalisti_data': giornalisti_data,
        'articoli_del_giorno': articoli_del_giorno,
        'articoli_periodo': articoli_periodo,
        'articoli_giornalisti_nati': articoli_giornalisti_nati,
        'giornalista_giovane': giornalista_giovane,
        'giornalista_anziano': giornalista_anziano,
        'ultimi_5_articoli': ultimi_5_articoli,
        'articoli_minime_visualizzazioni': articoli_minime_visualizzazioni,
        'articoli_parola': articoli_parola,
        'artioli_mese_anno': artioli_mese_anno,
        'giornalisti_con_articoli_popolari': giornalisti_con_articoli_popolari,
        'articoli_con_and': articoli_con_and,
        'articoli_con_or': articoli_con_or,
        'articoli_con_not': articoli_con_not
    }

    return render(request, 'query_base.html', context)

news/templates/news/articolo_detail.html
{% extends "base.html"%}

{% block title%} {{block.super}} | {{ giornalista.nome }} {{ giornalista.cognome }} {% endblock title%}

{% block content%}
    <h1>{{ articolo.titolo }}</h1>
    <h3>{{ articolo.contenuto }}</h3>
    <h5>Autore: {{ articolo.giornalista }}</h5>
{% endblock content%}

news/templates/news/giornalista_detail.html
{% extends "base.html"%}

{% block title%} {{block.super}} | {{ articolo.titolo }} {% endblock title%}

{% block content%}
    <h1>Dettagli del giornalista:</h1>
    <h1>{{ giornalista.nome }} {{ giornalista.cognome }}</h1>
    <h1>Nato il {{ giornalista.anno_di_nascita }}</h1>
    <h3>Tutti i suoi articoli e visualizzazioni:</h3>
    <ul>
        {% for articolo in articoli %}
            <li><strong>Titolo:</strong> <a href="{% url 'news:articolo_detail' articolo.id %}">{{ articolo.titolo }}</a> - n.{{ articolo.visualizzazioni }}</li>
        {% endfor %}
    </ul>
{% endblock content%}

news/templates/news/homepage.html
{% extends "base.html"%}

{% block title%} {{block.super}} | Articoli e Giornalisti {% endblock title%}

{% block content%}
    <h4>Articoli:</h4>
    {% for articolo in articoli %}
        <p><strong>Id: </strong><a href="../articolo/{{ articolo.id }}">{{ articolo.id }}</a></p>
        <p><strong>Titolo: </strong>{{ articolo.titolo }}</p>
        <p><strong>Contenuto: </strong>{{ articolo.contenuto }}</p>
        <p><strong>Autore: </strong>{{ articolo.giornalista }}</p>

        <hr>
    {% endfor %}
    <h4>Giornalisti:</h4>
    {% for giornalista in giornalisti %}
        <p><strong>Id: </strong><a href="../lista_articoli/{{ giornalista.id }}">{{ giornalista.id }}</a></p>
        <p><strong>Nome: </strong>{{ giornalista.nome }}</p>
        <p><strong>Cognome: </strong>{{ giornalista.cognome }}</p>
        <hr>
    {% endfor %}

{% endblock content%}

news/templates/news/index.html
{% extends "base.html"%}

{% block title%} {{block.super}} | INDEX NEWS {% endblock title%}

{% block content%}
    <ol>
        <li><a href="/">Index root</a></li>
        <li><a href="{% url 'news:homepage'%}">Homepage</a></li>
        <li><a href="{% url 'news:lista_articoli'%}">Lista articoli</a></li>
        <li><a href="{% url 'news:query_base'%}">Query Base</a></li>
    </ol>
{% endblock content%}

news/templates/news/lista_articoli.html
{% extends "base.html"%}

{% block title%} {{block.super}} | Lista Articoli {% endblock title%}

{% block content%}
    {% if is_vuoto %}
        <h1>Nessun articolo trovato</h1>
    {% else %}
        {% if is_giornalista %}
            <h1>Articoli di un giornalista:</h1>
        {% else %}
            <h1>Tutti gli articoli:</h1>
        {% endif %}
    {% endif %}

    {% for articolo in articoli %}
        <h5><b>Titolo:</b> <a href="../articolo/{{ articolo.id }}">{{ articolo.titolo }}</a></h5>
        <h5><b>Contenuto:</b> {{ articolo.contenuto }}</h5>
        <h5><b>Autore:</b> <a href="{% url 'news:giornalista_detail' articolo.giornalista.id %}">{{ articolo.giornalista }}</a></h5>
        <hr>
    {% endfor %}
{% endblock content%}

news/templates/news/query_base.html
{% extends "base.html"%}

{% block title%}
    {{ block.super }} | Articoli e Giornalisti
{% endblock title%}

{% block content%}

    <h2>Articoli e statistiche</h2>

    <h4>1. Articoli scritti da giornalisti con un certo cognome</h4>
    {% for articolo in articoli_cognome %}
        <p><strong>Id: </strong><a href="../articolo/{{ articolo.id }}">{{ articolo.id }}</a></p>
        <p><strong>Titolo: </strong>{{ articolo.titolo }}</p>
        <p><strong>Contenuto: </strong>{{ articolo.contenuto }}</p>
        <p><strong>Autore: </strong>{{ articolo.giornalista }}</p>
    {% endfor %}
    <hr>

    <h4>2. Numero totale di articoli</h4>
    <p>{{ numero_totale_articoli }}</p>
    <hr>

    <h4>3. Numero articoli del giornalista con ID = 1</h4>
    <p>{{ numero_articoli_giornalista_1 }}</p>
    <hr>

    <h4>4. Articoli ordinati per visualizzazioni (decrescente)</h4>
    {% for articolo in articoli_ordinati %}
        <p>{{ articolo.titolo }} – {{ articolo.visualizzazioni }} visualizzazioni</p>
    {% endfor %}
    <hr>

    <h4>5. Articoli senza visualizzazioni</h4>
    {% for articolo in articoli_senza_visualizzazioni %}
        <p>{{ articolo.titolo }}</p>
    {% endfor %}
    <hr>

    <h4>6. Articolo più visualizzato</h4>
        <p>
            {{ articolo_piu_visualizzato.titolo }}
            ({{ articolo_piu_visualizzato.visualizzazioni }} visualizzazioni)
        </p>
    <hr>

    <h4>7. Giornalisti nati dopo il 1990</h4>
    {% for giornalista in giornalisti_data %}
        <p>{{ giornalista.nome }} {{ giornalista.cognome }} ({{ giornalista.anno_di_nascita }})</p>
    {% endfor %}
    <hr>

    <h4>8. Articoli pubblicati il 01/01/2023</h4>
    {% for articolo in articoli_del_giorno %}
        <p>{{ articolo.titolo }}</p>
    {% endfor %}
    <hr>

    <h4>9. Articoli pubblicati nel 2023</h4>
    {% for articolo in articoli_periodo %}
        <p>{{ articolo.titolo }} – {{ articolo.data }}</p>
    {% endfor %}
    <hr>

    <h4>10. Articoli di giornalisti nati prima del 1980</h4>
    {% for articolo in articoli_giornalisti_nati %}
        <p>{{ articolo.titolo }} – {{ articolo.giornalista }}</p>
    {% endfor %}
    <hr>

    <h4>11. Giornalista più giovane</h4>
    <p>{{ giornalista_giovane.nome }} {{ giornalista_giovane.cognome }}</p>
    <hr>

    <h4>12. Giornalista più anziano</h4>
    {% if giornalista_anziano %}
        <p>{{ giornalista_anziano.nome }} {{ giornalista_anziano.cognome }}</p>
    {% endif %}
    <hr>

    <h4>13. Ultimi 5 articoli pubblicati</h4>
    {% for articolo in ultimi_5_articoli %}
        <p>{{ articolo.titolo }} – {{ articolo.data }}</p>
    {% endfor %}
    <hr>

    <h4>14. Articoli con almeno 100 visualizzazioni</h4>
    {% for articolo in articoli_minime_visualizzazioni %}
        <p>{{ articolo.titolo }} ({{ articolo.visualizzazioni }})</p>
    {% endfor %}
    <hr>

    <h4>15. Articoli che contengono la parola "importante" nel titolo</h4>
    {% for articolo in articoli_parola %}
        <p>{{ articolo.titolo }}</p>
    {% endfor %}
    <hr>

    <h4>16. Articoli pubblicati in un certo mese di un anno specifico</h4>
    {% for articolo in articoli_mese_anno %}
        <p>{{ articolo.titolo }}</p>
    {% endfor %}
    <hr>

    <h4>17. Giornalista con almeno un articolo con più di 100 visualizzazioni</h4>
    {% for giornalista in giornalisti_con_articoli_popolari %}
        <p>{{ giornalista.nome }} {{ giornalista.cognome }} ({{ giornalista.anno_di_nascita }})</p>
    {% endfor %}
    <hr>

    <h4>18. Utilizzo di piú condizioni con AND</h4>
    {% for articolo in articoli_con_and %}
        <p>{{ articolo.titolo }}</p>
    {% endfor %}
    <hr>

    <h4>19. Utilizzo di piú condizioni con OR</h4>
    {% for articolo in articoli_con_or %}
        <p>{{ articolo.titolo }}</p>
    {% endfor %}
    <hr>

    <h4>20. Condizione con NOT</h4>
    {% for articolo in articoli_con_not %}
        <p>{{ articolo.titolo }}</p>
    {% endfor %}


{% endblock content%}