news/urls.py
from django.urls import path
from news.views import *

app_name = "news"
urlpatterns = [
    path('', index, name='index'),
    path('homepage/', home, name='homepage'),
    path("articolo/<int:pk>", articoloDetailView, name="articolo_detail"),
    path("giornalista/<int:pk>", giornalistaDetailView, name="giornalista_detail"),
    path("lista_articoli/", listaArticoli, name="lista_articoli"),
    path("lista_articoli/<int:pk>", listaArticoli, name="lista_articoli"),
    path("query_base/", queryBase, name="query_base"),
]

prima_app/urls.py
from django.urls import path
from prima_app.views import homepage, welcome, lista, variabili, index, chi_siamo
app_name = "prima_app"
urlpatterns = [
    path('homepage', homepage, name="homepage"),
    path('welcome', welcome, name="welcome"),
    path('lista', lista, name="lista"),
    path('variabili', variabili, name="variabili"),
    path('chi_siamo', chi_siamo, name="chi_siamo"),
    path('', index, name="index"),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from primo_progetto.views import index_root

urlpatterns = [
    path('', index_root),
    path('admin/', admin.site.urls),
    path('prima_app/', include("prima_app.urls", namespace="prima_app")),
    path('seconda_app/', include("seconda_app.urls", namespace="seconda_app")),
    path('prova_pratica_0/', include("prova_pratica_0.urls", namespace="prova_pratica_0")),
    path('news/', include("news.urls", namespace="news")),
    path('voti/', include("voti.urls", namespace="voti")),
]

prova_pratica_0/urls.py
from django.urls import path
from prova_pratica_0.views import *
app_name = "prova_pratica_0"
urlpatterns = [
    path('', index, name="index"),
    path('somma', somma, name="somma"),
    path('media', media, name="media"),
]

seconda_app/urls.py
from django.urls import path
from seconda_app.views import es_if, if_else_elif, es_for, index

app_name = "seconda_app"
urlpatterns = [
    path('es_if', es_if, name="es_if"),
    path('if_else_elif', if_else_elif, name="if_else_elif"),
    path('es_for', es_for, name="es_for"),
    path('', index, name="index"),
]

voti/urls.py
from django.urls import path
from voti.views import *
app_name = "voti"
urlpatterns = [
    path('', index, name="index"),
    path('lista_materie', view_a, name="lista_materie"),
    path('lista_voti_assenze', view_b, name="lista_voti_assenze"),
    path('lista_medie', view_c, name="lista_medie"),
    path('max_min_voti', view_d, name="max_min_voti"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="it">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{% block title %} Primo progetto {% endblock title %}</title>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
</head>
<body>
<!-- navbar compressa, al suo interno è presente il menù -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="/">Primo progetto</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <!-- Dropdown prima app-->
                <a class="nav-link dropdown-toggle" href="#" id="primaAppDropdownMenuLink" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Prima App
                </a>
                <div class="dropdown-menu" aria-labelledby="primaAppDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'prima_app:index'%}">Index</a>
                    <a class="dropdown-item" href="{% url 'prima_app:homepage'%}">Home page</a>
                    <a class="dropdown-item" href="{% url 'prima_app:chi_siamo'%}">Chi siamo</a>
                    <a class="dropdown-item" href="{% url 'prima_app:welcome'%}">Welcome</a>
                    <a class="dropdown-item" href="{% url 'prima_app:lista'%}">Lista</a>
                    <a class="dropdown-item" href="{% url 'prima_app:variabili'%}">Variabili</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <!-- Dropdown seconda app-->
                <a class="nav-link dropdown-toggle" href="#" id="secondaAppDropdownMenuLink" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Seconda App
                </a>
                <div class="dropdown-menu" aria-labelledby="secondaAppDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'seconda_app:index'%}">Index</a>
                    <a class="dropdown-item" href="{% url 'seconda_app:es_if'%}">Esempio If</a>
                    <a class="dropdown-item" href="{% url 'seconda_app:if_else_elif'%}">Esempio If Else e Elif</a>
                    <a class="dropdown-item" href="{% url 'seconda_app:es_for'%}">Esempio for</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <!-- Dropdown seconda app-->
                <a class="nav-link dropdown-toggle" href="#" id="provaPratica0DropdownMenuLink" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Prova Pratica 0
                </a>
                <div class="dropdown-menu" aria-labelledby="provaPratica0DropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'prova_pratica_0:index'%}">Index</a>
                    <a class="dropdown-item" href="{% url 'prova_pratica_0:somma'%}">Somma</a>
                    <a class="dropdown-item" href="{% url 'prova_pratica_0:media'%}">Media</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <!-- Dropdown seconda app-->
                <a class="nav-link dropdown-toggle" href="#" id="newsDropdownMenuLink" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    News
                </a>
                <div class="dropdown-menu" aria-labelledby="newsDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'news:index'%}">Index</a>
                    <a class="dropdown-item" href="{% url 'news:homepage'%}">Homepage</a>
                    <a class="dropdown-item" href="{% url 'news:lista_articoli'%}">Lista Articoli</a>
                    <a class="dropdown-item" href="{% url 'news:query_base'%}">Query Base</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <!-- Dropdown seconda app-->
                <a class="nav-link dropdown-toggle" href="#" id="votiDropdownMenuLink" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    News
                </a>
                <div class="dropdown-menu" aria-labelledby="votiDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'voti:index'%}">Index</a>
                    <a class="dropdown-item" href="{% url 'voti:lista_materie'%}">Lista Materie</a>
                    <a class="dropdown-item" href="{% url 'voti:lista_voti_assenze'%}">Lista Voti Assenze</a>
                    <a class="dropdown-item" href="{% url 'voti:lista_medie'%}">Lista Medie</a>
                    <a class="dropdown-item" href="{% url 'voti:max_min_voti'%}">Min Max Voti</a>
                </div>
            </li>
        </ul>
    </div>
</nav>
<div class="container my-4">
    <!-- Servirà per inserire i contenuti della pagina -->
    {% block content %}
    {% endblock content %}
    <!-- Servirà per inserire il codice javascript -->
    {% block script %}
    {% endblock script %}
</div>


</body>
</html>

templates/index_root.html
{% extends "base.html"%}

{% block title%} {{block.super}} | ROOT MENU {% endblock title%}

{% block content%}
    <ol>
        <li><a href="/admin">Pannello admin</a></li>
        <li><a href="{% url 'prima_app:index'%}">Index prima app</a></li>
        <li><a href="{% url 'seconda_app:index'%}">Index seconda app</a></li>
        <li><a href="{% url 'prova_pratica_0:index'%}">Index prova pratica 0</a></li>
        <li><a href="{% url 'news:index'%}">Index news</a></li>
        <li><a href="{% url 'voti:index'%}">Index voti</a></li>
    </ol>
{% endblock content%}